package config

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

type ServerConfig struct {
	Host string `json:"host"`
	Port int    `json:"port"`
}

type DatabaseConfig struct {
	Path string `json:"path"`
}

type DocumentConfig struct {
	Formats      []string `json:"formats"`
	Watermark    string   `json:"watermark"`
	PremiumPrice float64  `json:"premium_price"`
}

type PaymentConfig struct {
	Currency string `json:"currency"`
}

type Config struct {
	Server   ServerConfig   `json:"server"`
	Database DatabaseConfig `json:"database"`
	Document DocumentConfig `json:"document"`
	Payment  PaymentConfig  `json:"payment"`
}

func Load(configPath string) (*Config, error) {
	cfg := defaultConfig()

	if configPath == "" {
		if _, err := os.Stat("config.json"); err == nil {
			configPath = "config.json"
		}
	}

	if configPath != "" {
		if err := loadFromFile(configPath, cfg); err != nil {
			return nil, err
		}
	}

	applyEnvOverrides(cfg)
	normalize(cfg)
	return cfg, nil
}

func defaultConfig() *Config {
	return &Config{
		Server:   ServerConfig{Host: "0.0.0.0", Port: 8080},
		Database: DatabaseConfig{Path: "data/app.json"},
		Document: DocumentConfig{Formats: []string{"pdf", "docx"}, Watermark: "Generated by law_for_it", PremiumPrice: 19.99},
		Payment:  PaymentConfig{Currency: "EUR"},
	}
}

func loadFromFile(path string, cfg *Config) error {
	data, err := os.ReadFile(path)
	if err != nil {
		return fmt.Errorf("failed to read config file: %w", err)
	}

	switch strings.ToLower(filepath.Ext(path)) {
	case ".json", "":
		if err := json.Unmarshal(data, cfg); err != nil {
			return fmt.Errorf("failed to parse config file: %w", err)
		}
	default:
		return fmt.Errorf("unsupported config format: %s", path)
	}
	return nil
}

func applyEnvOverrides(cfg *Config) {
	if host := os.Getenv("SERVER_HOST"); host != "" {
		cfg.Server.Host = host
	}
	if port := os.Getenv("SERVER_PORT"); port != "" {
		if p, err := strconv.Atoi(port); err == nil {
			cfg.Server.Port = p
		}
	}
	if dbPath := os.Getenv("DATABASE_PATH"); dbPath != "" {
		cfg.Database.Path = dbPath
	}
	if formats := os.Getenv("DOCUMENT_FORMATS"); formats != "" {
		cfg.Document.Formats = strings.Split(formats, ",")
	}
	if watermark := os.Getenv("DOCUMENT_WATERMARK"); watermark != "" {
		cfg.Document.Watermark = watermark
	}
	if price := os.Getenv("DOCUMENT_PREMIUM_PRICE"); price != "" {
		if value, err := strconv.ParseFloat(price, 64); err == nil {
			cfg.Document.PremiumPrice = value
		}
	}
	if currency := os.Getenv("PAYMENT_CURRENCY"); currency != "" {
		cfg.Payment.Currency = currency
	}
}

func normalize(cfg *Config) {
	cfg.Document.Formats = uniqueLower(cfg.Document.Formats)
	if len(cfg.Document.Formats) == 0 {
		cfg.Document.Formats = []string{"pdf"}
	}
}

func uniqueLower(values []string) []string {
	seen := make(map[string]struct{})
	result := make([]string, 0, len(values))
	for _, value := range values {
		lower := strings.ToLower(strings.TrimSpace(value))
		if lower == "" {
			continue
		}
		if _, ok := seen[lower]; ok {
			continue
		}
		seen[lower] = struct{}{}
		result = append(result, lower)
	}
	return result
}
